#!/usr/bin/env python3
"""Validate fixed-record fanfold reports generated by test-service."""

from pathlib import Path


RECORD_BYTES = 82
TEXT_BYTES = 80
SYSTEM_HEADING = b"CALENDAR MANAGEMENT SYSTEM"


def validate(
    path: Path,
    report_id: bytes,
    title: bytes,
    client_column: int | None,
) -> None:
    data = path.read_bytes()

    if not data or len(data) % RECORD_BYTES:
        raise SystemExit(
            f"{path}: report is not made of 80-column CR/LF records"
        )

    records = [
        data[i:i + RECORD_BYTES]
        for i in range(0, len(data), RECORD_BYTES)
    ]

    for number, record in enumerate(records, 1):
        if len(record) != RECORD_BYTES:
            raise SystemExit(
                f"{path}: invalid record length at line {number}"
            )

        if record[TEXT_BYTES:] != b"\r\n":
            raise SystemExit(
                f"{path}: invalid line ending at line {number}"
            )

    page_starts = [
        index
        for index, record in enumerate(records)
        if record[:TEXT_BYTES].startswith(SYSTEM_HEADING)
    ]

    if not page_starts:
        raise SystemExit(
            f"{path}: report contains no page heading"
        )

    if page_starts[0] != 0:
        raise SystemExit(
            f"{path}: first page does not start with the system heading"
        )

    for page_number, start in enumerate(page_starts, 1):
        heading = records[start][:TEXT_BYTES]

        if report_id not in heading:
            raise SystemExit(
                f"{path}: missing report ID on page {page_number}"
            )

        if start + 1 >= len(records):
            raise SystemExit(
                f"{path}: missing report title on page {page_number}"
            )

        title_line = records[start + 1][:TEXT_BYTES]

        if title not in title_line:
            raise SystemExit(
                f"{path}: missing report title on page {page_number}"
            )

    end_marker = b"*** END OF REPORT " + report_id + b" ***"

    marker_positions = [
        index
        for index, record in enumerate(records)
        if end_marker in record[:TEXT_BYTES]
    ]

    if len(marker_positions) != 1:
        raise SystemExit(
            f"{path}: expected exactly one end-of-report marker"
        )

    marker = marker_positions[0]

    if marker < page_starts[-1]:
        raise SystemExit(
            f"{path}: end-of-report marker precedes final page"
        )

    if any(
        record[:TEXT_BYTES].strip()
        for record in records[marker + 1:]
    ):
        raise SystemExit(
            f"{path}: non-blank data follows end-of-report marker"
        )

    if client_column is not None and not any(
        record[
            client_column:client_column + 11
        ] == b"TEST CLIENT"
        for record in records
    ):
        raise SystemExit(
            f"{path}: appointment content is missing"
        )

    if b"000000001" in data:
        raise SystemExit(
            f"{path}: internal appointment ID leaked into print layout"
        )


validate(
    Path("build/test-service.txt"),
    b"CALR01",
    b"APPOINTMENT CALENDAR",
    None,
)

validate(
    Path("build/test-service-list.txt"),
    b"CALR02",
    b"APPOINTMENT LIST",
    31,
)

print("fanfold report geometry: PASS")
