#!/usr/bin/env python3
"""Validate fixed-record fanfold reports generated by test-service."""
from pathlib import Path

RECORD_BYTES = 82
TEXT_BYTES = 80
LINES_PER_PAGE = 20


def validate(path: Path, heading: bytes, footer: bytes, client_column: int | None) -> None:
    data = path.read_bytes()
    if not data or len(data) % RECORD_BYTES:
        raise SystemExit(f"{path}: report is not made of 80-column CR/LF records")
    records = [data[i : i + RECORD_BYTES] for i in range(0, len(data), RECORD_BYTES)]
    if len(records) % LINES_PER_PAGE:
        raise SystemExit(f"{path}: incomplete fanfold page")
    for number, record in enumerate(records, 1):
        if len(record[:TEXT_BYTES]) != TEXT_BYTES or record[TEXT_BYTES:] != b"\r\n":
            raise SystemExit(f"{path}: invalid fixed record at line {number}")
    for page_start in range(0, len(records), LINES_PER_PAGE):
        page = records[page_start : page_start + LINES_PER_PAGE]
        heading_line = 0 if page_start == 0 else 1
        if not page[heading_line].startswith(heading):
            raise SystemExit(f"{path}: missing page heading")
        if not page[-2].startswith(footer) or page[-1][:TEXT_BYTES].strip():
            raise SystemExit(f"{path}: invalid page footer or bottom margin")
    if client_column is not None and not any(
        record[client_column : client_column + 11] == b"TEST CLIENT" for record in records
    ):
        raise SystemExit(f"{path}: appointment content is missing")
    if b"000000001" in data:
        raise SystemExit(f"{path}: internal appointment ID leaked into print layout")


validate(
    Path("build/test-service.txt"),
    b"APPOINTMENT CALENDAR",
    b"REPORT APPT01 / END PAGE",
    None,
)
validate(
    Path("build/test-service-list.txt"),
    b"APPOINTMENT LIST",
    b"REPORT APPT02 / END PAGE",
    31,
)
print("fanfold report geometry: PASS")
