#!/usr/bin/env python3
"""Validate fixed-record fanfold reports generated by test-service."""

from pathlib import Path

RECORD_BYTES = 82
TEXT_BYTES = 80
LINES_PER_PAGE = 20


def validate(
    path: Path,
    title: bytes,
    report_id: bytes,
    end_marker: bytes,
    client_column: int | None,
) -> None:
    data = path.read_bytes()

    if not data or len(data) % RECORD_BYTES:
        raise SystemExit(
            f"{path}: report is not made of 80-column CR/LF records"
        )

    records = [
        data[i : i + RECORD_BYTES]
        for i in range(0, len(data), RECORD_BYTES)
    ]

    if len(records) % LINES_PER_PAGE:
        raise SystemExit(f"{path}: incomplete fanfold page")

    for number, record in enumerate(records, 1):
        if (
            len(record[:TEXT_BYTES]) != TEXT_BYTES
            or record[TEXT_BYTES:] != b"\r\n"
        ):
            raise SystemExit(
                f"{path}: invalid fixed record at line {number}"
            )

    page_count = len(records) // LINES_PER_PAGE

    for page_number in range(page_count):
        page_start = page_number * LINES_PER_PAGE
        page = records[page_start : page_start + LINES_PER_PAGE]

        # First page starts immediately with the heading.
        # Continuation pages have one blank top-margin line.
        heading_line = 0 if page_number == 0 else 1
        title_line = heading_line + 1

        if not page[heading_line].startswith(
            b"CALENDAR MANAGEMENT SYSTEM"
        ):
            raise SystemExit(
                f"{path}: missing system heading on page "
                f"{page_number + 1}"
            )

        if report_id not in page[heading_line]:
            raise SystemExit(
                f"{path}: missing report id on page "
                f"{page_number + 1}"
            )

        if not page[title_line].startswith(title):
            raise SystemExit(
                f"{path}: missing report title on page "
                f"{page_number + 1}"
            )

        # Last physical line is always blank.
        if page[-1][:TEXT_BYTES].strip():
            raise SystemExit(
                f"{path}: invalid bottom margin on page "
                f"{page_number + 1}"
            )

        # Only the final page carries the end-of-report marker.
        if page_number == page_count - 1:
            if not page[-2].startswith(end_marker):
                raise SystemExit(
                    f"{path}: missing final report marker"
                )
        else:
            if page[-2][:TEXT_BYTES].strip():
                raise SystemExit(
                    f"{path}: unexpected footer on page "
                    f"{page_number + 1}"
                )

    if client_column is not None and not any(
        record[client_column : client_column + 11] == b"TEST CLIENT"
        for record in records
    ):
        raise SystemExit(
            f"{path}: appointment content is missing"
        )

    if b"000000001" in data:
        raise SystemExit(
            f"{path}: internal appointment ID leaked into print layout"
        )


validate(
    Path("build/test-service.txt"),
    b"APPOINTMENT CALENDAR",
    b"REPORT CALR01",
    b"*** END OF REPORT CALR01 ***",
    None,
)

validate(
    Path("build/test-service-list.txt"),
    b"APPOINTMENT LIST",
    b"REPORT CALR02",
    b"*** END OF REPORT CALR02 ***",
    31,
)

print("fanfold report geometry: PASS")
